### ISSUE TITLE
Pypiper should utilize pipestat to report results

### ISSUE THREAD

**Issue by donaldcampbelljr** [databio/pypiper#187]
Related to:
https://github.com/pepkit/pipestat/issues/21

Currently, Pypiper uses function `_safe_write_to_file` to write items to a local file. However, Pypiper should use pipestat.report instead.

As a specific example `stats` are written to a stats.tsv file in a table format:

```
key1    abc    sample_pipeline
key2    def    shared

```

Using pipestat.report from within a Pypiper pipeline manager can be used to write stats:

```
default_pipeline_name:
  project: {}
  sample:
    sample_pipeline:
      Result: key1    abc    sample_pipeline

```
